### ISSUE TITLE
Marking articles as optional to read

### ISSUE THREAD

**Issue by BroBQ** [Xeverous/Xeverous.github.io#15]
I'm sure that few articles are not compulsory e.g. macros (and surely more). Tagging them as "optional" would be helpful for readers if they will rush through chapters.

**Comment by Xeverous** [comment]
It's already being done where appropriate. Macros are simple to understand and still a lot of today's code uses them (especially testing/logging stuff).

There are some articles (missing) in the tutorial that will be optional since usage of presented features is rather rare (eg bit fields).

Some articles may describe legacy and/or deprecated features (eg dynamic exception specification), some may describe upcoming features (eg concepts, 3-way comparison) - all of them will have an explicit note that they are about past/future content.
